### PR TITLE
LESSON 3 TASK2

### PR DESCRIPTION
**Pull request by chidinmaamara**
@ChidiPatrick
@Promise-J
Group A

### CODE REVIEW

**Review by promise-J — CHANGES_REQUESTED** [review]
Please fix your live link in your README.md file. It says page is not found.

**Comment by chidinmaamara** [comment]
review @ChidiP
@promise-J 
GroupA

**Comment by promise-J** [comment]
I don't see the link to the pull request please

**Comment by chidinmaamara** [comment]
> Please fix your live link in your README.md file. It says page is not found.

i have put the link

**Review by promise-J — APPROVED** [review]
Give the content a reasonable padding. Clear to Merge

**Pull request merged**
